# -*- coding: utf-8 -*-
"""
Nomenclature officielle "Nature de prestation" du formulaire BDC de
marchespublics.gov.ma (339 entrees, dropdown
search_consultation_entreprise[naturePrestation]). Reference statique,
extraite directement du HTML reel le 2026-06-28 (pas saisie a la main).

Contrairement a la taxonomie AO (app.core.taxonomie), cette liste est
PLATE (pas de sous-domaines) et contient des doublons par organisme
(suffixe "(ONDA)"/"(ANCFCC)" -- meme activite, mais l'organisme a sa
propre entree dans le dropdown source). On NE deduplique PAS : le champ
`nature_prestation` scrape sur un BDC contient le libelle EXACT choisi
par l'acheteur, donc le filtre doit matcher la valeur litterale stockee.

`categorie` (Travaux/Fournitures/Services) classee par mots-cles
(verbe/nom d'ouverture du libelle) -- cf. session 2026-06-28. Le code
est l'identifiant numerique natif du dropdown source (string, stable).
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class NaturePrestation:
    code: str
    label: str
    categorie: str
    """L'une des 3 valeurs de app.core.taxonomie.CATEGORIES."""


NATURES_PRESTATION: tuple[NaturePrestation, ...] = (
    NaturePrestation("1", "Travaux d’aménagement des espaces verts avec ou sans fourniture de graines et plantes", "Travaux"),
    NaturePrestation("2", "Travaux d’aménagement et d’entretien des installations militaires", "Travaux"),
    NaturePrestation("3", "Travaux d’aménagement, d’entretien et de réparation des bâtiments administratifs", "Travaux"),
    NaturePrestation("4", "Travaux d’aménagement, d’entretien et de réparation des logements militaires", "Travaux"),
    NaturePrestation("5", "Travaux d’aménagement, d’entretien et de réparation des ouvrages, voies et réseaux", "Travaux"),
    NaturePrestation("6", "Travaux d’équipement et de renforcement des postes MT/BT du réseau d’électricité", "Travaux"),
    NaturePrestation("7", "Travaux d’installation de matériels divers", "Travaux"),
    NaturePrestation("8", "Travaux de branchement et d’extension du réseau d’eau potable et d’électricité", "Travaux"),
    NaturePrestation("9", "Travaux de raccordement au réseau d’assainissement et de curage", "Travaux"),
    NaturePrestation("10", "Achat d’affiches et d’articles publicitaires", "Fournitures"),
    NaturePrestation("11", "Achat d’animaux", "Fournitures"),
    NaturePrestation("12", "Achat d’articles de correction de la vue et articles pour personnes à besoins spécifiques", "Fournitures"),
    NaturePrestation("13", "Achat d’articles de droguerie, de quincaillerie, d’électricité, de menuiserie et de plomberie sanitaire", "Fournitures"),
    NaturePrestation("14", "Achat d’habillement", "Fournitures"),
    NaturePrestation("15", "Achat de badges, de médailles, d’effigies, de fanions, de drapeaux et de portraits", "Fournitures"),
    NaturePrestation("16", "Achat de carburants et de lubrifiants", "Fournitures"),
    NaturePrestation("17", "Achat de cartables, de livres, de manuels, et de fournitures scolaires et de matériel d’enseignement", "Fournitures"),
    NaturePrestation("18", "Achat de cartes géographiques, topographiques, géologiques et de photographies aériennes", "Fournitures"),
    NaturePrestation("19", "Achat de fournitures de bureau et de documentation", "Fournitures"),
    NaturePrestation("20", "Achat de matériaux de construction", "Fournitures"),
    NaturePrestation("21", "Achat de matériel audiovisuel, sonore et de mise en lumière", "Fournitures"),
    NaturePrestation("22", "Achat de matériel d’éclairage public", "Fournitures"),
    NaturePrestation("23", "Achat de matériel de diagnostic, de recherche, de détection, de signalisation de défaut et de matériel de mesure", "Fournitures"),
    NaturePrestation("24", "Achat de matériel de navigation et de transmission", "Fournitures"),
    NaturePrestation("25", "Achat de matériel de sécurité et de lutte contre l’incendie", "Fournitures"),
    NaturePrestation("26", "Achat de matériel de transport, de citernes et d’engins", "Fournitures"),
    NaturePrestation("27", "Achat de matériel électrique, de groupes électrogènes, d’électropompes et de motopompes de chantier", "Fournitures"),
    NaturePrestation("28", "Achat de matériel et d’équipement de plongée sous-marine", "Fournitures"),
    NaturePrestation("29", "Achat de matériel et de mobilier de bureau", "Fournitures"),
    NaturePrestation("30", "Achat de matériel technique, de logiciels et de matériel informatique", "Fournitures"),
    NaturePrestation("31", "Achat de matériel, de câbles, coffrets de distribution, de poteaux et autres accessoires de branchements moyenne tension et basse tension", "Fournitures"),
    NaturePrestation("32", "Achat de matériels et articles de sport, de literie, de linge, de couchage, de cuisine et de buanderie", "Fournitures"),
    NaturePrestation("33", "Achat de matières premières pour laboratoire et enseignement", "Fournitures"),
    NaturePrestation("34", "Achat de matières premières pour le textile, le cuir, la reliure des documents et autres", "Fournitures"),
    NaturePrestation("35", "Achat de médicaments", "Fournitures"),
    NaturePrestation("36", "Achat de mobilier, d’enseignement, de laboratoire et d’exposition", "Fournitures"),
    NaturePrestation("37", "Achat de papeteries et d’imprimés", "Fournitures"),
    NaturePrestation("38", "Achat de pièces de rechange et pneumatiques pour véhicules et engins", "Fournitures"),
    NaturePrestation("39", "Achat de pièces de rechange pour les équipements médicotechniques", "Fournitures"),
    NaturePrestation("40", "Achat de pièces de rechange pour matériel technique et informatique", "Fournitures"),
    NaturePrestation("41", "Achat de produits alimentaires pour usage animal", "Fournitures"),
    NaturePrestation("42", "Achat de produits alimentaires pour usage humain", "Fournitures"),
    NaturePrestation("43", "Achat de produits chimiques et de laboratoire, pesticides et insecticides", "Fournitures"),
    NaturePrestation("44", "Achat de produits d’impression, de reproduction et de photographie", "Fournitures"),
    NaturePrestation("45", "Achat de produits pharmaceutiques non-médicamenteux, de gaz médicaux et de réactifs de laboratoires", "Fournitures"),
    NaturePrestation("46", "Achat de produits pour traitement d’eau potable", "Fournitures"),
    NaturePrestation("47", "Achat de produits vétérinaires et de produits d’élevage aquacole", "Fournitures"),
    NaturePrestation("48", "Fourniture d’alevins, de naissains, de boutures d’algues, d’animaux marins et poissons", "Fournitures"),
    NaturePrestation("49", "Fourniture d’engrais, de graines, de plantes, de plants et de portoirs", "Fournitures"),
    NaturePrestation("50", "Fourniture d’équipements médico-techniques et de pièces de rechange y afférentes", "Fournitures"),
    NaturePrestation("51", "Fourniture de combustibles et de produits de chauffage", "Fournitures"),
    NaturePrestation("52", "Fourniture de films et de produits radiologiques", "Fournitures"),
    NaturePrestation("53", "Fourniture de fongibles médicaux et de fils chirurgicaux", "Fournitures"),
    NaturePrestation("54", "Fourniture de l’instrumentation médicotechnique", "Fournitures"),
    NaturePrestation("55", "Fourniture de prothèses et orthèses", "Fournitures"),
    NaturePrestation("56", "Fourniture de sacs et produits d’emballage", "Fournitures"),
    NaturePrestation("57", "Fourniture de verrerie, petit matériel et outillage de laboratoire", "Fournitures"),
    NaturePrestation("58", "Fourniture des consommables dentaires", "Fournitures"),
    NaturePrestation("59", "Fournitures et pièces de rechange pour matériel technique et informatique", "Fournitures"),
    NaturePrestation("60", "Fournitures et produits d’entretien et de nettoyage", "Fournitures"),
    NaturePrestation("61", "Fournitures pour inauguration et pose de premières pierres", "Fournitures"),
    NaturePrestation("62", "Fournitures pour le traitement et la conservation préventive des archives", "Fournitures"),
    NaturePrestation("63", "Achat de piges", "Services"),
    NaturePrestation("64", "Achat, développement, production ou coproduction de programmes ou de films destinés à la diffusion par des organismes de radiodiffusion et de télévision et dans les sites électroniques et du temps de diffusion", "Services"),
    NaturePrestation("65", "Collecte des produits biologiques et sanguins", "Services"),
    NaturePrestation("66", "Contrôle et expertise techniques", "Services"),
    NaturePrestation("67", "Direction, animation et participation des artistes, intellectuels, conférenciers et techniciens aux manifestations et activités culturelles", "Services"),
    NaturePrestation("68", "Entretien et maintenance de logiciels et de progiciels", "Services"),
    NaturePrestation("69", "Entretien et maintenance des équipements informatique", "Services"),
    NaturePrestation("70", "Entretien et réparation de matériel technique, de mobilier et des installations techniques", "Services"),
    NaturePrestation("71", "Entretien, dépoussiérage et traitement chimique des archives et des livres", "Services"),
    NaturePrestation("72", "Études, conseil et formation", "Services"),
    NaturePrestation("73", "Location d’engins et de moyens de transport de matériels et matériaux et d’engins", "Services"),
    NaturePrestation("74", "Location de camions citernes", "Services"),
    NaturePrestation("75", "Location de matériel et de mobilier", "Services"),
    NaturePrestation("76", "Location de moyens de transport des personnes (voitures et autocars)", "Services"),
    NaturePrestation("77", "Location de salles, de stands et de mobilier d’exposition", "Services"),
    NaturePrestation("78", "Montage et démontage du matériel hydraulique et électromécanique", "Services"),
    NaturePrestation("79", "Organisation de manifestations culturelles, scientifiques et sportives", "Services"),
    NaturePrestation("80", "Prestation de jardinage, de gardiennage et de nettoyage", "Services"),
    NaturePrestation("81", "Prestations d’assistance et de conseil technique, juridique et comptable", "Services"),
    NaturePrestation("82", "Prestations d’entretien des véhicules et engins", "Services"),
    NaturePrestation("83", "Prestations d’entretien, de rééquilibrage, d’étalonnage et de réparation des équipements de laboratoires", "Services"),
    NaturePrestation("84", "Prestations d’impression, de tirage, de reproduction et de photographie", "Services"),
    NaturePrestation("85", "Prestations de centres d’appels, de télémarketing et de télé-service", "Services"),
    NaturePrestation("86", "Prestations de collecte et de traitement de déchets hospitaliers", "Services"),
    NaturePrestation("87", "Prestations de collecte, de traitement et de blanchissage du linge", "Services"),
    NaturePrestation("88", "Prestations de contrôle des points de comptage", "Services"),
    NaturePrestation("89", "Prestations de contrôle et d’analyse des échantillons prélevés sur les produits, matériel et matériaux soumis à des normes obligatoires", "Services"),
    NaturePrestation("90", "Prestations de déménagement", "Services"),
    NaturePrestation("91", "Prestations de désinsectisation, de dératisation et prestations de lutte contre les animaux errants", "Services"),
    NaturePrestation("92", "Prestations de mise en place des outils de gestion technique et de détection de fuites", "Services"),
    NaturePrestation("93", "Prestations de publicité, de sensibilisation et supports multimédia", "Services"),
    NaturePrestation("94", "Prestations de remise en état et de recharge des extincteurs", "Services"),
    NaturePrestation("95", "Prestations d’hôtellerie, d’hébergement, de réception et de restauration", "Services"),
    NaturePrestation("96", "Prestations géotechniques et de laboratoire", "Services"),
    NaturePrestation("97", "Prestations médicales, hospitalières, radiologiques, d’analyse médicale et de brancardage", "Services"),
    NaturePrestation("98", "Prestations topographiques et océanographiques", "Services"),
    NaturePrestation("99", "Traduction simultanée et traduction des documents et des œuvres littéraires, scientifiques, culturelles ou juridiques", "Services"),
    NaturePrestation("100", "Transport, acconage, magasinage et transit", "Services"),
    NaturePrestation("101", "Travaux d’aménagement, d’entretien et de réparation des bâtiments administratifs (ONDA)", "Travaux"),
    NaturePrestation("102", "Travaux d’aménagement, d’entretien et de réparation des bâtiments techniques (ONDA)", "Travaux"),
    NaturePrestation("103", "Travaux d’aménagement, d’entretien et de réparation des bâtiments à caractère social (logements d’estivage, centres sportifs, cantines, buvettes et autres) (ONDA)", "Travaux"),
    NaturePrestation("104", "Travaux d’aménagement, d’entretien et de réparation des ouvrages, voies et réseaux (ONDA)", "Travaux"),
    NaturePrestation("105", "Travaux d’entretien et de maintenance des réseaux et des espaces verts (ONDA)", "Travaux"),
    NaturePrestation("106", "Travaux d’aménagement des espaces verts avec ou sans fourniture de graines et plantes (ONDA)", "Travaux"),
    NaturePrestation("107", "Travaux d’installation de matériels divers (ONDA)", "Travaux"),
    NaturePrestation("108", "Travaux de dégommage des pistes d’envol (ONDA)", "Travaux"),
    NaturePrestation("109", "Travaux d’entretien des infrastructures aéroportuaires, de leurs équipements et de leurs dépendances (ONDA)", "Travaux"),
    NaturePrestation("110", "Travaux de signalétique et de signalisation (ONDA)", "Travaux"),
    NaturePrestation("111", "Travaux d’assainissement, de raccordement au réseau d’assainissement et de curage (ONDA)", "Travaux"),
    NaturePrestation("112", "Travaux d’équipement et de renforcement des postes MT/BT du réseau d’électricité (ONDA)", "Travaux"),
    NaturePrestation("113", "Travaux de branchement et d’extension du réseau d’eau potable et d’électricité (ONDA)", "Travaux"),
    NaturePrestation("114", "Achat d’articles pour relations publiques (ONDA)", "Fournitures"),
    NaturePrestation("115", "Acquisition de licences de conception des procédures (ONDA)", "Fournitures"),
    NaturePrestation("116", "Animaux (ONDA)", "Fournitures"),
    NaturePrestation("117", "Articles de cuisine (ONDA)", "Fournitures"),
    NaturePrestation("118", "Articles de literie, de lingerie, de couchage et de buanderie (ONDA)", "Fournitures"),
    NaturePrestation("119", "Articles d’habillement du personnel (ONDA)", "Fournitures"),
    NaturePrestation("120", "Articles de plomberie sanitaire (ONDA)", "Fournitures"),
    NaturePrestation("121", "Batteries (ONDA)", "Fournitures"),
    NaturePrestation("122", "Carburants et lubrifiants (ONDA)", "Fournitures"),
    NaturePrestation("123", "Cartes géographiques, topographiques et géologiques, photographies aériennes (ONDA)", "Fournitures"),
    NaturePrestation("124", "Fournitures et produits de nettoyage (ONDA)", "Fournitures"),
    NaturePrestation("125", "Documentation (ONDA)", "Fournitures"),
    NaturePrestation("126", "Equipements de protection individuelle (EPI) (ONDA)", "Fournitures"),
    NaturePrestation("127", "Fourniture d’engrais, de graines, plantes, fleurs, plants, portoirs (ONDA)", "Fournitures"),
    NaturePrestation("128", "Fourniture d’équipements médicotechniques (ONDA)", "Fournitures"),
    NaturePrestation("129", "Fourniture de badge, articles similaires et accessoires (ONDA)", "Fournitures"),
    NaturePrestation("130", "Fourniture pour matériel informatique et bureautique (ONDA)", "Fournitures"),
    NaturePrestation("131", "Fournitures de bureau et imprimés (ONDA)", "Fournitures"),
    NaturePrestation("132", "Fournitures de clôtures grillagées et barbelés pour sécurité des sites (ONDA)", "Fournitures"),
    NaturePrestation("133", "Fournitures de composants électriques (chargeurs, onduleurs, régulateurs, batteries) destinés aux installations de la navigation aérienne (ONDA)", "Fournitures"),
    NaturePrestation("134", "Fournitures de sacs et produits d’emballage (ONDA)", "Fournitures"),
    NaturePrestation("135", "Fournitures du matériel pour le système de téléaffichage et le système de traitement de passagers (ONDA)", "Fournitures"),
    NaturePrestation("136", "Fournitures électriques (ONDA)", "Fournitures"),
    NaturePrestation("137", "Fournitures pour matériel technique et informatique (ONDA)", "Fournitures"),
    NaturePrestation("138", "Achat de cartables, de livres, de manuels, et de fournitures scolaires et de matériel d’enseignement (ONDA)", "Fournitures"),
    NaturePrestation("139", "Matériaux de construction (ONDA)", "Fournitures"),
    NaturePrestation("140", "Matériel de sonorisation de téléphonie et de télécommunication (ONDA)", "Fournitures"),
    NaturePrestation("141", "Matériel de transport (ONDA)", "Fournitures"),
    NaturePrestation("142", "Matériel et articles de sport (ONDA)", "Fournitures"),
    NaturePrestation("143", "Matériel informatique et pièces de rechange (ONDA)", "Fournitures"),
    NaturePrestation("144", "Matériel médical pour unité médicale d’urgence (ONDA)", "Fournitures"),
    NaturePrestation("145", "Matériel technique et d’assainissement (ONDA)", "Fournitures"),
    NaturePrestation("146", "Matériels de lutte contre l’incendie (ONDA)", "Fournitures"),
    NaturePrestation("147", "Badges, médailles, effigies, drapeaux, fanions et portraits (ONDA)", "Fournitures"),
    NaturePrestation("148", "Médicaments (ONDA)", "Fournitures"),
    NaturePrestation("149", "Mobilier d’aérogare (ONDA)", "Fournitures"),
    NaturePrestation("150", "Mobilier de bureau (ONDA)", "Fournitures"),
    NaturePrestation("151", "Matériel de bureau (ONDA)", "Fournitures"),
    NaturePrestation("152", "Autres mobiliers (ONDA)", "Fournitures"),
    NaturePrestation("153", "Autres matériels (ONDA)", "Fournitures"),
    NaturePrestation("154", "Droguerie, outillage et quincaillerie (ONDA)", "Fournitures"),
    NaturePrestation("155", "Fourniture de peinture et ses produits accessoires (ONDA)", "Fournitures"),
    NaturePrestation("156", "Pièces de rechange et fournitures électriques pour l’éclairage des grandes surfaces et aérogares (ONDA)", "Fournitures"),
    NaturePrestation("157", "Pièces de rechange et fournitures pour climatisation et matériel de climatisation (ONDA)", "Fournitures"),
    NaturePrestation("158", "Pièces de rechange et fournitures pour installations communication, navigation et surveillances (ONDA)", "Fournitures"),
    NaturePrestation("159", "Pièces de rechange et fournitures pour installations de navigation aérienne (ONDA)", "Fournitures"),
    NaturePrestation("160", "Pièces de rechange et fournitures pour matériel et de balisage (ONDA)", "Fournitures"),
    NaturePrestation("161", "Pièces de rechange pour les équipements médicotechniques (ONDA)", "Fournitures"),
    NaturePrestation("162", "Pièces de rechange pour matériel technique (ONDA)", "Fournitures"),
    NaturePrestation("163", "Pièces de rechange, fournitures et pneumatiques pour véhicules et engins (ONDA)", "Fournitures"),
    NaturePrestation("164", "Produits alimentaires pour usage humain et animal (ONDA)", "Fournitures"),
    NaturePrestation("165", "Produits chimiques et de laboratoire, pesticides et insecticides (ONDA)", "Fournitures"),
    NaturePrestation("166", "Produits d’impression, de reproduction et de photographie (ONDA)", "Fournitures"),
    NaturePrestation("167", "Fourniture de combustibles et de produits de chauffage (ONDA)", "Fournitures"),
    NaturePrestation("168", "Produits de lutte contre l’incendie (ONDA)", "Fournitures"),
    NaturePrestation("169", "Produits pharmaceutiques non médicamenteux, articles de correction de vue et articles pour handicapés (ONDA)", "Fournitures"),
    NaturePrestation("170", "Systèmes vidéo surveillance (ONDA)", "Fournitures"),
    NaturePrestation("171", "Mobilier d’exposition (ONDA)", "Fournitures"),
    NaturePrestation("172", "Signalétique et signalisation (ONDA)", "Fournitures"),
    NaturePrestation("173", "Articles d’électroménager (ONDA)", "Fournitures"),
    NaturePrestation("174", "Fourniture pour ateliers mécaniques, de menuiserie et de tôlerie (ONDA)", "Fournitures"),
    NaturePrestation("175", "Gaz et Oxygène (ONDA)", "Fournitures"),
    NaturePrestation("176", "Mobiliers pour bâtiments à caractère social (ONDA)", "Fournitures"),
    NaturePrestation("177", "Matériels et équipements pour bâtiments à caractère social (ONDA)", "Fournitures"),
    NaturePrestation("178", "Achat de logiciels (ONDA)", "Fournitures"),
    NaturePrestation("179", "Articles d’habillement des élèves de l’AIAC (ONDA)", "Fournitures"),
    NaturePrestation("180", "Articles d’habillement pour actions sociales (ONDA)", "Fournitures"),
    NaturePrestation("181", "Matériel et article de sport pour les élèves de l’AIAC (ONDA)", "Fournitures"),
    NaturePrestation("182", "Literies pour les élèves de l’AIAC (ONDA)", "Fournitures"),
    NaturePrestation("183", "Matériel de manutention, citernes et engins (ONDA)", "Fournitures"),
    NaturePrestation("184", "Matériel et installations logistiques (ONDA)", "Fournitures"),
    NaturePrestation("185", "Achat d’affiches et d’articles publicitaires (ONDA)", "Fournitures"),
    NaturePrestation("186", "Matériel audiovisuel, sonore et de mise en lumière (ONDA)", "Fournitures"),
    NaturePrestation("187", "Matériel électrique, de groupes électrogènes, d’électropompes et de motopompes (ONDA)", "Fournitures"),
    NaturePrestation("188", "Matériel, de câbles, coffrets de distribution, de poteaux et autres accessoires de branchements moyenne tension et basse tension (ONDA)", "Fournitures"),
    NaturePrestation("189", "Animation colonie de vacances (ONDA)", "Services"),
    NaturePrestation("190", "Capture des animaux (ONDA)", "Services"),
    NaturePrestation("191", "Contrôle réglementaire et veille légale et réglementaire (ONDA)", "Services"),
    NaturePrestation("192", "Dégraissage et nettoyage (ONDA)", "Services"),
    NaturePrestation("193", "Elaboration du plan de dégagement de servitude radioélectrique pour installations communication, navigation et surveillances (ONDA)", "Services"),
    NaturePrestation("194", "Entretien et réparation de matériel et de mobilier (ONDA)", "Services"),
    NaturePrestation("195", "Entretien et réparation des équipements et installation technique (ONDA)", "Services"),
    NaturePrestation("196", "Entretien et réparation des groupes électrogène et onduleurs (ONDA)", "Services"),
    NaturePrestation("197", "Entretien et réparation des véhicules et engins (ONDA)", "Services"),
    NaturePrestation("198", "Etalonnage et calibrage des appareils de mesure (ONDA)", "Services"),
    NaturePrestation("199", "Etudes et conseil (ONDA)", "Services"),
    NaturePrestation("200", "Location d’engins et de moyens de transport de matériels et matériaux et d’engins (ONDA)", "Services"),
    NaturePrestation("201", "Location de camion citernes (ONDA)", "Services"),
    NaturePrestation("202", "Location de matériel et de mobilier (ONDA)", "Services"),
    NaturePrestation("203", "Location de moyens de transport des personnes (voitures et cars) (ONDA)", "Services"),
    NaturePrestation("204", "Location de tentes, chapiteaux et toilettes mobiles (ONDA)", "Services"),
    NaturePrestation("205", "Montage et démontage du matériel hydraulique et électromécanique (ONDA)", "Services"),
    NaturePrestation("206", "Organisation de manifestations culturelles, scientifiques et sportives (ONDA)", "Services"),
    NaturePrestation("207", "Prestation de formation et coaching (ONDA)", "Services"),
    NaturePrestation("208", "Prestation de montage, démontage et pointage antenne (VHF, FH et VSAT) (ONDA)", "Services"),
    NaturePrestation("209", "Prestation de réfection et peinture des pylônes des antennes avancées (ONDA)", "Services"),
    NaturePrestation("210", "Prestation médicale, hospitalières et de brancardage (ONDA)", "Services"),
    NaturePrestation("211", "Prestations d’assistance et de conseil (ONDA)", "Services"),
    NaturePrestation("212", "Prestations d’assistance au recrutement (ONDA)", "Services"),
    NaturePrestation("213", "Prestations d’enquête cadastrale et parcellaire (ONDA)", "Services"),
    NaturePrestation("214", "Prestations d’impression, de reproduction, de photographie et de tournage (ONDA)", "Services"),
    NaturePrestation("215", "Prestations de jardinage des aérogares et bâtiments (ONDA)", "Services"),
    NaturePrestation("216", "Prestations de nettoyage (ONDA)", "Services"),
    NaturePrestation("217", "Prestations de collecte de déchets (ONDA)", "Services"),
    NaturePrestation("218", "Prestations d’intérim (ONDA)", "Services"),
    NaturePrestation("219", "Prestations de mesure, d’analyse et de contrôle (mesure de la qualité d’air, rejets liquides, contrôle qualité de l’eau, mesure du niveau du bruit) et prestations traitement des déchets (ONDA)", "Services"),
    NaturePrestation("220", "Prestations de publicité (ONDA)", "Services"),
    NaturePrestation("221", "Prestations topographiques (ONDA)", "Services"),
    NaturePrestation("222", "Réparation et maintenance des équipements techniques, informatiques, logiciels et progiciels (ONDA)", "Services"),
    NaturePrestation("223", "Traduction des documents et correspondances (ONDA)", "Services"),
    NaturePrestation("224", "Transport, acconage, magasinage et transit (ONDA)", "Services"),
    NaturePrestation("225", "Visite technique des véhicules et engins (ONDA)", "Services"),
    NaturePrestation("226", "Prestations de gardiennage et de surveillance (ONDA)", "Services"),
    NaturePrestation("227", "Gestion multiservices des bâtiments (ONDA)", "Services"),
    NaturePrestation("228", "Audits (ONDA)", "Services"),
    NaturePrestation("229", "Prestations d’accréditation et de certification (ONDA)", "Services"),
    NaturePrestation("230", "Prestations de centres d’appels (ONDA)", "Services"),
    NaturePrestation("231", "Veille et gestion de la marque ONDA sur les réseaux sociaux (ONDA)", "Services"),
    NaturePrestation("232", "Prestations liées à l’obtention d’un certificat et signature électronique (ONDA)", "Services"),
    NaturePrestation("233", "Assistance administrative, technique et logistique pour la réforme des immobilisations (ONDA)", "Services"),
    NaturePrestation("234", "Prestations de remise en état et de recharge des extincteurs (ONDA)", "Services"),
    NaturePrestation("235", "Travaux d’aménagement des espaces verts avec ou sans fourniture de graines et plantes (ANCFCC)", "Travaux"),
    NaturePrestation("236", "Travaux d’aménagement, d’entretien et de réparation des bâtiments administratifs (ANCFCC)", "Travaux"),
    NaturePrestation("237", "Travaux d’aménagement, d’entretien et de réparation des ouvrages, voies et réseaux (ANCFCC)", "Travaux"),
    NaturePrestation("238", "Travaux d’équipement et de renforcement des postes MT/BT du réseau d’électricité (ANCFCC)", "Travaux"),
    NaturePrestation("239", "Travaux d’installation de matériels divers (ANCFCC)", "Travaux"),
    NaturePrestation("240", "Travaux de branchement et d’extension du réseau d’eau potable et d’électricité (ANCFCC)", "Travaux"),
    NaturePrestation("241", "Travaux de raccordement au réseau d’assainissement et de curage (ANCFCC)", "Travaux"),
    NaturePrestation("242", "Travaux d’aménagement, d’entretien et de réparation des bâtiments administratifs et techniques (ANCFCC)", "Travaux"),
    NaturePrestation("243", "Achat d’affiches et d’articles publicitaires (ANCFCC)", "Fournitures"),
    NaturePrestation("244", "Achat d’animaux (ANCFCC)", "Fournitures"),
    NaturePrestation("245", "Achat d’articles de correction de la vue et articles pour personnes à besoins spécifiques (ANCFCC)", "Fournitures"),
    NaturePrestation("246", "Achat d’articles de droguerie, de quincaillerie, d’électricité, de menuiserie et de plomberie sanitaire (ANCFCC)", "Fournitures"),
    NaturePrestation("247", "Achat d’habillement (ANCFCC)", "Fournitures"),
    NaturePrestation("248", "Achat de badges, de médailles, d’effigies, de fanions, de drapeaux et de portraits (ANCFCC)", "Fournitures"),
    NaturePrestation("249", "Achat de carburants et de lubrifiants (ANCFCC)", "Fournitures"),
    NaturePrestation("250", "Achat de cartables, de livres, de manuels, et de fournitures scolaires et de matériel d’enseignement (ANCFCC)", "Fournitures"),
    NaturePrestation("251", "Achat de cartes géographiques, topographiques, géologiques et de photographies aériennes (ANCFCC)", "Fournitures"),
    NaturePrestation("252", "Achat de fournitures de bureau et de documentation (ANCFCC)", "Fournitures"),
    NaturePrestation("253", "Achat de matériaux de construction (ANCFCC)", "Fournitures"),
    NaturePrestation("254", "Achat de matériel audiovisuel, sonore et de mise en lumière (ANCFCC)", "Fournitures"),
    NaturePrestation("255", "Achat de matériel d’éclairage public (ANCFCC)", "Fournitures"),
    NaturePrestation("256", "Achat de matériel de diagnostic, de recherche, de détection, de signalisation de défaut et de matériel de mesure (ANCFCC)", "Fournitures"),
    NaturePrestation("257", "Achat de matériel de navigation et de transmission (ANCFCC)", "Fournitures"),
    NaturePrestation("258", "Achat de matériel de sécurité et produits de lutte contre l’incendie (ANCFCC)", "Fournitures"),
    NaturePrestation("259", "Achat de matériel électrique, de groupes électrogènes, d’électropompes et de motopompes de chantier (ANCFCC)", "Fournitures"),
    NaturePrestation("260", "Achat de matériel et de mobilier de bureau (ANCFCC)", "Fournitures"),
    NaturePrestation("261", "Achat de matériel technique, de logiciels et de matériel informatique (ANCFCC)", "Fournitures"),
    NaturePrestation("262", "Achat de matériel, de câbles, coffrets de distribution, de poteaux et autres accessoires de branchements moyenne tension et basse tension (ANCFCC)", "Fournitures"),
    NaturePrestation("263", "Achat de matériels et articles de sport, de literie, de linge, de couchage, de cuisine et de buanderie (ANCFCC)", "Fournitures"),
    NaturePrestation("264", "Achat de matières premières pour laboratoire et enseignement (ANCFCC)", "Fournitures"),
    NaturePrestation("265", "Achat de matières premières pour le textile, le cuir, la reliure des documents et autres (ANCFCC)", "Fournitures"),
    NaturePrestation("266", "Achat de médicaments (ANCFCC)", "Fournitures"),
    NaturePrestation("267", "Achat de mobilier, d’enseignement, de laboratoire et d’exposition (ANCFCC)", "Fournitures"),
    NaturePrestation("268", "Achat de papeteries et d’imprimés (ANCFCC)", "Fournitures"),
    NaturePrestation("269", "Achat de pièces de rechange et pneumatiques pour véhicules et engins (ANCFCC)", "Fournitures"),
    NaturePrestation("270", "Achat de pièces de rechange pour les équipements médicotechniques (ANCFCC)", "Fournitures"),
    NaturePrestation("271", "Achat de pièces de rechange pour matériel technique et informatique (ANCFCC)", "Fournitures"),
    NaturePrestation("272", "Achat de produits alimentaires pour usage animal (ANCFCC)", "Fournitures"),
    NaturePrestation("273", "Achat de produits alimentaires pour usage humain (ANCFCC)", "Fournitures"),
    NaturePrestation("274", "Achat de produits chimiques et de laboratoire, pesticides et insecticides (ANCFCC)", "Fournitures"),
    NaturePrestation("275", "Achat de produits d’impression, de reproduction et de photographie (ANCFCC)", "Fournitures"),
    NaturePrestation("276", "Achat de produits pharmaceutiques non-médicamenteux, de gaz médicaux et de réactifs de laboratoires (ANCFCC)", "Fournitures"),
    NaturePrestation("277", "Achat de produits pour traitement d’eau potable (ANCFCC)", "Fournitures"),
    NaturePrestation("278", "Cartes géographiques, topographiques et géologiques, photographies aériennes et images satellitaires (ANCFCC)", "Fournitures"),
    NaturePrestation("279", "Détergents et produits de nettoyage (ANCFCC)", "Fournitures"),
    NaturePrestation("280", "Fourniture d’engrais, de graines, de plantes, de plants et de portoirs (ANCFCC)", "Fournitures"),
    NaturePrestation("281", "Fourniture d’équipements médicotechniques et de pièces de rechange y afférentes (ANCFCC)", "Fournitures"),
    NaturePrestation("282", "Fourniture de combustibles et de produits de chauffage (ANCFCC)", "Fournitures"),
    NaturePrestation("283", "Fourniture de films et de produits radiologiques (ANCFCC)", "Fournitures"),
    NaturePrestation("284", "Fourniture de sacs et produits d’emballage (ANCFCC)", "Fournitures"),
    NaturePrestation("285", "Fourniture de verrerie, petit matériel et outillage de laboratoire (ANCFCC)", "Fournitures"),
    NaturePrestation("286", "Fournitures et pièces de rechange pour matériel technique et informatique (ANCFCC)", "Fournitures"),
    NaturePrestation("287", "Fournitures et produits d’entretien et de nettoyage (ANCFCC)", "Fournitures"),
    NaturePrestation("288", "Fournitures pour inauguration et pose de premières pierres (ANCFCC)", "Fournitures"),
    NaturePrestation("289", "Fournitures pour le traitement et la conservation préventive des archives (ANCFCC)", "Fournitures"),
    NaturePrestation("290", "Fournitures de reliure, de reprographie, de reproduction, de photomécanique (ANCFCC)", "Fournitures"),
    NaturePrestation("291", "Fournitures électriques (ANCFCC)", "Fournitures"),
    NaturePrestation("292", "Fournitures pour matériel informatique et technique (ANCFCC)", "Fournitures"),
    NaturePrestation("293", "Fourniture de pièces de rechange pour matériel d’imprimerie (ANCFCC)", "Fournitures"),
    NaturePrestation("294", "Fourniture de pièces de rechange pour matériel cartographique (ANCFCC)", "Fournitures"),
    NaturePrestation("295", "Fourniture de pièces de rechange pour matériel géodésique (ANCFCC)", "Fournitures"),
    NaturePrestation("296", "Habillement (ANCFCC)", "Fournitures"),
    NaturePrestation("297", "Manuels et fournitures scolaires et d’enseignement (ANCFCC)", "Fournitures"),
    NaturePrestation("298", "Matériel d’imprimerie (ANCFCC)", "Fournitures"),
    NaturePrestation("299", "Matériel géodésique et accessoires (ANCFCC)", "Fournitures"),
    NaturePrestation("300", "Matériel cartographique et accessoires (ANCFCC)", "Fournitures"),
    NaturePrestation("301", "Outillage et quincaillerie (ANCFCC)", "Fournitures"),
    NaturePrestation("302", "Abonnement aux prestations liées aux avions (ANCFCC)", "Services"),
    NaturePrestation("303", "Actions de communication et relations publiques (ANCFCC)", "Services"),
    NaturePrestation("304", "Achat de piges (ANCFCC)", "Services"),
    NaturePrestation("305", "Contrôle et expertise techniques (ANCFCC)", "Services"),
    NaturePrestation("306", "Direction, animation et participation des artistes, intellectuels, conférenciers et techniciens aux manifestations et activités culturelles (ANCFCC)", "Services"),
    NaturePrestation("307", "Entretien et maintenance des équipements cartographiques, système de flashage et équipements géodésiques (ANCFCC)", "Services"),
    NaturePrestation("308", "Entretien et maintenance de logiciels et de progiciels (ANCFCC)", "Services"),
    NaturePrestation("309", "Entretien et maintenance des équipements informatiques (ANCFCC)", "Services"),
    NaturePrestation("310", "Entretien et réparation de matériel technique, de mobilier et des installations techniques (ANCFCC)", "Services"),
    NaturePrestation("311", "Entretien, dépoussiérage et traitement chimique des archives et des livres (ANCFCC)", "Services"),
    NaturePrestation("312", "Etudes, conseil et formation (ANCFCC)", "Services"),
    NaturePrestation("313", "Location d’engins et de moyens de transport de matériels et matériaux et d’engins (ANCFCC)", "Services"),
    NaturePrestation("314", "Location de camions citernes (ANCFCC)", "Services"),
    NaturePrestation("315", "Location de matériel et de mobilier (ANCFCC)", "Services"),
    NaturePrestation("316", "Location de moyens de transport des personnes (voitures et autocars) (ANCFCC)", "Services"),
    NaturePrestation("317", "Montage et démontage du matériel hydraulique et électromécanique (ANCFCC)", "Services"),
    NaturePrestation("318", "Organisation de manifestations culturelles, scientifiques et sportives (ANCFCC)", "Services"),
    NaturePrestation("319", "Prestation de jardinage, de gardiennage, de nettoyage et d’intérim (ANCFCC)", "Services"),
    NaturePrestation("320", "Prestations d’assistance et de conseil technique, juridique et comptable (ANCFCC)", "Services"),
    NaturePrestation("321", "Prestations d’entretien des véhicules et engins (ANCFCC)", "Services"),
    NaturePrestation("322", "Prestations d’impression, de tirage, de reproduction et de photographie (ANCFCC)", "Services"),
    NaturePrestation("323", "Prestations de centres d’appels, de télémarketing et de télé-service (ANCFCC)", "Services"),
    NaturePrestation("324", "Prestations de contrôle et d’analyse des échantillons prélevés sur les produits, matériel et matériaux soumis à des normes obligatoires (ANCFCC)", "Services"),
    NaturePrestation("325", "Prestations de déménagement (ANCFCC)", "Services"),
    NaturePrestation("326", "Prestations de désinsectisation, de dératisation et prestations de lutte contre les animaux errants (ANCFCC)", "Services"),
    NaturePrestation("327", "Prestations de mise en place des outils de gestion technique et de détection de fuites (ANCFCC)", "Services"),
    NaturePrestation("328", "Prestations de publicité, de sensibilisation et supports multimédia (ANCFCC)", "Services"),
    NaturePrestation("329", "Prestations de remise en état et de recharge des extincteurs (ANCFCC)", "Services"),
    NaturePrestation("330", "Prestations géotechniques et de laboratoire (ANCFCC)", "Services"),
    NaturePrestation("331", "Prestations médicales, hospitalières, radiologiques, d’analyse médicale et de brancardage (ANCFCC)", "Services"),
    NaturePrestation("332", "Prestations topographiques et océanographiques (ANCFCC)", "Services"),
    NaturePrestation("333", "Transport, acconage, magasinage et transit. (ANCFCC)", "Services"),
    NaturePrestation("334", "Prestations d’installation et de mise en service des liens wan (ANCFCC)", "Services"),
    NaturePrestation("335", "Prestations d’audit et de contrôle de gestion (ANCFCC)", "Services"),
    NaturePrestation("336", "Prestations cartographiques et photogrammétriques (ANCFCC)", "Services"),
    NaturePrestation("337", "Prestations géodésiques (ANCFCC)", "Services"),
    NaturePrestation("338", "Prestations topographiques (ANCFCC)", "Services"),
    NaturePrestation("339", "Prestations de flashage et d’impression cartographique (ANCFCC)", "Services"),
)

NATURES_PRESTATION_BY_CODE: dict[str, NaturePrestation] = {
    n.code: n for n in NATURES_PRESTATION
}
